# Generated by Django 4.1 on 2022-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueño', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mascota', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=100)),
            ],
        ),
    ]
